module.exports = {
    DB_LOCAL:{
        type: "postgres",
        host: "localhost",
        port: 5432,
        username:"mobeet_server" ,
        password: "password",
        database: "mobeet",
        synchronize: false,
        migrations: ["database/migrations/*.js"],
        entities: ["database/models/**/*.js"],
    },
    DB_STAGING: {
        type: "postgres",
        host: "localhost",
        port: 5432,
        username: "mobeet_server",
        password: "password",
        database: "mobeet",
        synchronize: false,
        migrations: ["database/migrations/*.js"],
        entities: ["database/models/**/*.js"],
},
    DB_PRODUCTION: {
        type: "postgres",
        host: "localhost",
        port: 5432,
        username: "mobeet_server",
        password: "password",
        database: "mobeet",
        synchronize: false,
        migrations: ["database/migrations/*.js"],
        entities: ["database/models/**/*.js"],
}
}
